In [2]:
import xarray as xr

In [3]:
d_2018 = xr.open_dataset('2018.nc')
d_2019 = xr.open_dataset('2019.nc')
d_2020 = xr.open_dataset('2020.nc')
d_2021 = xr.open_dataset('2021.nc')
d_2022 = xr.open_dataset('2022.nc')
d_2023 = xr.open_dataset('2023.nc')

In [4]:
d_2022

<xarray.Dataset>
Dimensions:    (latitude: 125, longitude: 121, time: 730)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2022-01-01 ... 2022-12-31T12:00:00
Data variables:
    t2m        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-06-19 14:52:25 GMT by grib_to_netcdf-2.28.1: /opt/ecmw...

In [5]:
sum_2018 = d_2018['t2m'].sum().item()

In [6]:
sum_2018
print("Length of t2m : ",len(d_2018['t2m']))
print("Average : ",sum_2018/(124*121*125))

Length of t2m :  730
Average :  1722.510912290056


In [7]:
d_2018['t2m']

<xarray.DataArray 't2m' (time: 730, latitude: 125, longitude: 121)>
array([[[272.257  , 272.6281 , ..., 253.52705, 252.94325],
        [272.3083 , 272.84683, ..., 255.66464, 254.58453],
        ...,
        [300.02005, 300.00497, ..., 300.75168, 300.72153],
        [300.10904, 300.02307, ..., 300.72604, 300.68985]],

       [[285.91827, 286.89883, ..., 265.65717, 265.6979 ],
        [286.9094 , 287.2307 , ..., 264.88028, 264.73093],
        ...,
        [300.01553, 300.06833, ..., 301.36264, 301.24496],
        [300.09396, 300.16638, ..., 301.09564, 300.9689 ]],

       ...,

       [[274.08685, 273.73236, ..., 249.83717, 253.38223],
        [274.00992, 274.1321 , ..., 252.88593, 257.21088],
        ...,
        [299.23712, 299.32913, ..., 299.57806, 299.43475],
        [299.1285 , 299.1602 , ..., 299.52676, 299.4815 ]],

       [[283.8727 , 283.8003 , ..., 262.48926, 261.13156],
        [283.79425, 284.0145 , ..., 265.26645, 263.5437 ],
        ...,
        [299.41965, 299.3608 , ..., 300.91763, 300.82712],
        [299.6218 , 299.53882, ..., 300.97647, 300.86633]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2018-01-01 ... 2018-12-31T12:00:00
Attributes:
    units:      K
    long_name:  2 metre temperature

In [8]:
d_2019

<xarray.Dataset>
Dimensions:    (latitude: 125, longitude: 121, time: 730)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2019-01-01 ... 2019-12-31T12:00:00
Data variables:
    t2m        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-06-19 14:49:37 GMT by grib_to_netcdf-2.28.1: /opt/ecmw...

In [9]:
d_1990 = xr.open_dataset('1990.nc')

In [10]:
d_1990['t2m'].loc["1990-12-01":"1990-12-31"]

<xarray.DataArray 't2m' (time: 62, latitude: 125, longitude: 121)>
[937750 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 1990-12-01 ... 1990-12-31T12:00:00
Attributes:
    units:      K
    long_name:  2 metre temperature

In [11]:
a = d_2022['t2m'].loc["2022-12-01":"2022-12-31"]
a

<xarray.DataArray 't2m' (time: 62, latitude: 125, longitude: 121)>
[937750 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2022-12-01 ... 2022-12-31T12:00:00
Attributes:
    units:      K
    long_name:  2 metre temperature

In [12]:
b = d_2023['t2m'].loc["2023-12-01":"2023-12-31"]

In [13]:
a.combine_first(b)

<xarray.DataArray 't2m' (time: 124, latitude: 125, longitude: 121)>
array([[[282.7762 , 283.15704, 282.90118, ..., 262.5512 , 262.2284 ,
         264.00604],
        [282.94876, 282.05475, 281.26038, ..., 263.95547, 264.33032,
         264.2247 ],
        [281.66946, 280.4794 , 279.90817, ..., 266.00534, 266.0544 ,
         264.38538],
        ...,
        [299.85056, 299.74792, 299.7018 , ..., 299.617  , 299.8238 ,
         299.8952 ],
        [299.89072, 299.73602, 299.6646 , ..., 299.30164, 299.59024,
         299.8357 ],
        [300.08856, 299.9785 , 299.79254, ..., 299.03387, 299.21686,
         299.52777]],

       [[286.6454 , 286.632  , 286.64984, ..., 269.26608, 267.65506,
         266.9187 ],
        [285.31104, 285.1831 , 285.12213, ..., 269.3256 , 268.61008,
         268.0701 ],
        [282.43854, 282.77026, 282.9428 , ..., 270.86224, 269.9117 ,
         268.70676],
...
        [299.42163, 299.45663, 299.51642, ..., 301.0855 , 301.1074 ,
         301.0622 ],
        [299.50186, 299.47122, 299.5208 , ..., 300.99802, 301.0403 ,
         300.9922 ],
        [299.61267, 299.5879 , 299.56894, ..., 300.75302, 300.7545 ,
         300.68887]],

       [[284.84784, 284.26746, 285.4472 , ..., 267.58942, 266.87488,
         266.61093],
        [284.87994, 284.5737 , 284.55182, ..., 267.94086, 267.41296,
         267.1053 ],
        [283.4523 , 283.4523 , 283.64188, ..., 268.98935, 268.47165,
         267.24234],
        ...,
        [300.63638, 300.58972, 300.55472, ..., 301.3553 , 301.35675,
         301.39758],
        [300.6524 , 300.57513, 300.562  , ..., 301.35092, 301.3684 ,
         301.41217],
        [300.62033, 300.45117, 300.27036, ..., 301.3378 , 301.36258,
         301.418  ]]], dtype=float32)
Coordinates:
  * time       (time) datetime64[ns] 2022-12-01 ... 2023-12-31T12:00:00
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
Attributes:
    units:      K
    long_name:  2 metre temperature

In [14]:
a = a.to_numpy() + b.to_numpy()
a = xr.DataArray(a)
a

AttributeError: 'DataArray' object has no attribute 'to_numpy'

In [ ]:
d_2017 = xr.open_dataset('2017.nc')
d_2017['time']

<xarray.DataArray 'time' (time: 730)>
array(['2017-01-01T00:00:00.000000000', '2017-01-01T12:00:00.000000000',
       '2017-01-02T00:00:00.000000000', ..., '2017-12-30T12:00:00.000000000',
       '2017-12-31T00:00:00.000000000', '2017-12-31T12:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2017-01-01 ... 2017-12-31T12:00:00
Attributes:
    long_name:  time

In [ ]:
d_2017 = xr.open_dataset('2017.nc')
d_2017

<xarray.Dataset>
Dimensions:    (longitude: 121, latitude: 125, time: 730)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2017-01-01 ... 2017-12-31T12:00:00
Data variables:
    t2m        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-06-18 03:36:05 GMT by grib_to_netcdf-2.28.1: /opt/ecmw...

In [ ]:
d = xr.open_dataset('2018.nc')
d['time']

<xarray.DataArray 'time' (time: 730)>
array(['2018-01-01T00:00:00.000000000', '2018-01-01T12:00:00.000000000',
       '2018-01-02T00:00:00.000000000', ..., '2018-12-30T12:00:00.000000000',
       '2018-12-31T00:00:00.000000000', '2018-12-31T12:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 ... 2018-12-31T12:00:00
Attributes:
    long_name:  time

In [ ]:
d = d['t2m'].loc["2018-12-01":"2018-12-31"]

In [ ]:
l = d.sel(time=slice("2018-12-01","2018-12-01"))
m = d.sel(time=slice("2018-12-02","2018-12-02"))
m[0][1][1].item()

282.61309814453125

In [ ]:
a = l.sum(dim="time")
a = a / 2
b = l.sum(dim="time")
b = b / 2
a = a + b
a.rename()

<xarray.DataArray (latitude: 125, longitude: 121)>
array([[564.1476 , 565.06024, 565.57465, ..., 517.96533, 517.90045,
        523.8335 ],
       [563.4325 , 563.9439 , 563.72974, ..., 526.6138 , 522.31445,
        521.4304 ],
       [561.577  , 561.72034, 561.98584, ..., 532.67505, 528.4436 ,
        525.1203 ],
       ...,
       [600.562  , 600.3508 , 600.49414, ..., 601.5834 , 601.4657 ,
        601.21826],
       [600.46246, 600.4776 , 600.61633, ..., 600.808  , 600.73706,
        600.40967],
       [600.59375, 600.7461 , 601.1957 , ..., 600.4595 , 600.4806 ,
        600.1472 ]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0

In [ ]:
k = xr.concat([a,b],dim='time')
k

<xarray.DataArray 't2m' (time: 2, latitude: 125, longitude: 121)>
array([[[564.1476 , 565.06024, 565.57465, ..., 517.96533, 517.90045,
         523.8335 ],
        [563.4325 , 563.9439 , 563.72974, ..., 526.6138 , 522.31445,
         521.4304 ],
        [561.577  , 561.72034, 561.98584, ..., 532.67505, 528.4436 ,
         525.1203 ],
        ...,
        [600.562  , 600.3508 , 600.49414, ..., 601.5834 , 601.4657 ,
         601.21826],
        [600.46246, 600.4776 , 600.61633, ..., 600.808  , 600.73706,
         600.40967],
        [600.59375, 600.7461 , 601.1957 , ..., 600.4595 , 600.4806 ,
         600.1472 ]],

       [[282.0738 , 282.53012, 282.78732, ..., 258.98267, 258.95023,
         261.91675],
        [281.71625, 281.97195, 281.86487, ..., 263.3069 , 261.15723,
         260.7152 ],
        [280.7885 , 280.86017, 280.99292, ..., 266.33752, 264.2218 ,
         262.56015],
        ...,
        [300.281  , 300.1754 , 300.24707, ..., 300.7917 , 300.73285,
         300.60913],
        [300.23123, 300.2388 , 300.30817, ..., 300.404  , 300.36853,
         300.20483],
        [300.29688, 300.37305, 300.59784, ..., 300.22974, 300.2403 ,
         300.0736 ]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
Dimensions without coordinates: time

In [ ]:
d = d.sel(time=slice("2018-12-1","2018-12-1"))
d.min(dim='time')

<xarray.DataArray 't2m' (latitude: 125, longitude: 121)>
array([[281.4983 , 282.01572, 282.18015, ..., 256.65875, 257.0902 ,
        258.79333],
       [281.18298, 281.53146, 281.22372, ..., 259.80405, 258.41318,
        258.47202],
       [280.66406, 280.71835, 280.73648, ..., 262.4259 , 260.95508,
        260.6428 ],
       ...,
       [299.57956, 299.4091 , 299.45737, ..., 300.44547, 300.72302,
        300.4002 ],
       [299.61273, 299.5675 , 299.59464, ..., 299.57654, 299.9235 ,
        300.10754],
       [299.73193, 299.76962, 300.0095 , ..., 299.28088, 299.3382 ,
        299.48755]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0

In [ ]:
time_list = []
for x in range(1,32):
    time_list.append(f"12-{x}")
print(time_list)

['12-1', '12-2', '12-3', '12-4', '12-5', '12-6', '12-7', '12-8', '12-9', '12-10', '12-11', '12-12', '12-13', '12-14', '12-15', '12-16', '12-17', '12-18', '12-19', '12-20', '12-21', '12-22', '12-23', '12-24', '12-25', '12-26', '12-27', '12-28', '12-29', '12-30', '12-31']


In [ ]:
type('12-1')

str

In [ ]:
import numpy as np
x = np.random.choice([True,False],size = (31,125,121))
x

array([[[False, False, False, ...,  True,  True,  True],
        [False,  True, False, ..., False, False,  True],
        [False,  True,  True, ...,  True,  True, False],
        ...,
        [ True,  True,  True, ..., False, False, False],
        [ True,  True, False, ..., False, False,  True],
        [False,  True,  True, ...,  True,  True,  True]],

       [[False, False, False, ..., False,  True,  True],
        [False, False, False, ..., False,  True,  True],
        [False, False, False, ...,  True,  True, False],
        ...,
        [ True, False, False, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True, False],
        [False, False,  True, ..., False,  True, False]],

       [[ True,  True,  True, ..., False, False,  True],
        [ True, False, False, ..., False,  True, False],
        [False,  True, False, ...,  True, False,  True],
        ...,
        [False, False,  True, ..., False, False,  True],
        [ True, False,  True, ..., False,  Tr

In [ ]:
data = xr.open_dataset('2023.nc')
data

<xarray.Dataset>
Dimensions:    (longitude: 121, latitude: 125, time: 730)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2023-01-01 ... 2023-12-31T12:00:00
Data variables:
    t2m        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-06-19 14:52:51 GMT by grib_to_netcdf-2.28.1: /opt/ecmw...

In [ ]:
data = data.sel(time=slice("2023-12-01","2023-12-31"))
data = data.sel(longitude=slice(75.25,80.25),latitude=slice(31.25,26.25,1))
data = data - 273.15

In [ ]:
c = 0 
Agg = data.sel(time=['2023-12-01','2023-12-02','2023-12-03']).sum(dim='time')
Agg

<xarray.Dataset>
Dimensions:    (longitude: 21, latitude: 21)
Coordinates:
  * longitude  (longitude) float32 75.25 75.5 75.75 76.0 ... 79.75 80.0 80.25
  * latitude   (latitude) float32 31.25 31.0 30.75 30.5 ... 26.75 26.5 26.25
Data variables:
    t2m        (latitude, longitude) float32 37.37 36.12 37.74 ... 56.4 56.01

In [ ]:
Threshold = 40
for x in range(1,29):
    Agg = data.sel(time=[f'2023-12-{x}',f'2023-12-{x+1}',f'2023-12-{x+2}']).sum(dim='time')
    Agg = Agg < Threshold
    print(f'Places experiencing cold waves during 2023-12-{x} to 2023-12-{x+2}')
    for y in Agg['latitude']:
        for z in Agg['longitude']:
            if(Agg.sel(latitude=y,longitude=z) == True):
                print(f'Latitude : {y.item()} Longitude : {z.item()}')

Places experiencing cold waves during 2023-12-1 to 2023-12-3
Latitude : 31.25 Longitude : 75.25
Latitude : 31.25 Longitude : 75.5
Latitude : 31.25 Longitude : 75.75
Latitude : 31.25 Longitude : 76.0
Latitude : 31.25 Longitude : 76.25
Latitude : 31.25 Longitude : 76.5
Latitude : 31.25 Longitude : 76.75
Latitude : 31.25 Longitude : 77.0
Latitude : 31.25 Longitude : 77.25
Latitude : 31.25 Longitude : 77.5
Latitude : 31.25 Longitude : 77.75
Latitude : 31.25 Longitude : 78.0
Latitude : 31.25 Longitude : 78.25
Latitude : 31.25 Longitude : 78.5
Latitude : 31.25 Longitude : 78.75
Latitude : 31.25 Longitude : 79.0
Latitude : 31.25 Longitude : 79.25
Latitude : 31.25 Longitude : 79.5
Latitude : 31.25 Longitude : 79.75
Latitude : 31.25 Longitude : 80.0
Latitude : 31.25 Longitude : 80.25
Latitude : 31.0 Longitude : 75.25
Latitude : 31.0 Longitude : 75.5
Latitude : 31.0 Longitude : 75.75
Latitude : 31.0 Longitude : 76.0
Latitude : 31.0 Longitude : 76.25
Latitude : 31.0 Longitude : 76.5
Latitude : 31

In [ ]:
p = xr.open_dataset('Prediction.nc')

In [ ]:
time_slices = 2
d_2023 = xr.open_dataset('Prediction.nc')
d_2023 = d_2023['mean'].loc["2023-12-03":"2023-12-31"]

T_current_mean = d_2023.sel(time=slice("2023-12-03","2023-12-03"))
T_current_mean = T_current_mean.sum(dim="time")
T_current_mean = T_current_mean/time_slices

T_current_min = d_2023.sel(time=slice("2023-12-03","2023-12-31"))
T_current_min = T_current_min.min(dim="time")

for y in range(2,29*time_slices,time_slices):
    Vari_T = d_2023.sel(time=slice(f"2023-12-{int(y/2)}",f"2023-12-{int(y/2)}"))
    print(Vari_T)
    T_current_min = xr.concat([T_current_min,Vari_T.min(dim='time')],dim='time')
    Vari_T = Vari_T.sum(dim='time')
    Vari_T = Vari_T/time_slices
    T_current_mean = xr.concat([T_current_mean,Vari_T],dim='time')

<xarray.DataArray 'mean' (time: 0, latitude: 20, longitude: 21)>
array([], shape=(0, 20, 21), dtype=float32)
Coordinates:
  * latitude   (latitude) float64 26.38 26.62 26.88 27.12 ... 30.62 30.88 31.12
  * longitude  (longitude) float64 75.25 75.5 75.75 76.0 ... 79.75 80.0 80.25
  * time       (time) datetime64[ns] 


ValueError: numpy.nanmin raises on a.shape[axis]==0; So Bottleneck too.

In [ ]:
import xarray as xr

In [ ]:
P = xr.open_dataset('Prediction.nc')
for y in range(3,32):
    Vari_T = P.sel(time=slice(f"2023-12-{y}T00:00:00.000000000",f"2023-12-{y}T12:00:00.000000000"))
    print(Vari_T['mean'].sel(latitude=28.875,longitude=77.75)[0].item(),Vari_T['mean'].sel(latitude=28.875,longitude=77.75)[1].item())

12.222862243652344 20.1304874420166
14.563817977905273 19.424461364746094
12.528217315673828 19.171836853027344
11.953041076660156 19.767484664916992
12.070928573608398 19.972959518432617
11.589591979980469 18.755216598510742
11.046116828918457 18.919214248657227
11.61563491821289 19.037105560302734
8.960580825805664 18.944684982299805
8.434965133666992 18.152515411376953
8.797591209411621 17.155452728271484
9.28950309753418 17.934429168701172
8.894569396972656 17.3713436126709
9.796775817871094 16.859094619750977
7.823521614074707 16.77703094482422
10.162034034729004 18.333789825439453
10.338011741638184 18.447399139404297
nan nan
9.219230651855469 17.403711318969727
8.326038360595703 20.68490219116211
11.781272888183594 20.244871139526367
9.769720077514648 nan
nan nan
nan nan
nan nan
10.72490119934082 20.042022705078125
9.425079345703125 20.59328269958496
9.362268447875977 18.2218017578125
9.025634765625 16.136362075805664
