In [62]:
import xarray as xr

In [63]:
d_2018 = xr.open_dataset('2018.nc')
d_2019 = xr.open_dataset('2019.nc')
d_2020 = xr.open_dataset('2020.nc')
d_2021 = xr.open_dataset('2021.nc')
d_2022 = xr.open_dataset('2022.nc')
d_2023 = xr.open_dataset('2023.nc')

In [64]:
sum_2018 = d_2018['t2m'].sum().item()

In [65]:
sum_2018
print("Length of t2m : ",len(d_2018['t2m']))
print("Average : ",sum_2018/(124*121*125))

Length of t2m :  730
Average :  1722.510912290056


In [66]:
d_2018['t2m']

<xarray.DataArray 't2m' (time: 730, latitude: 125, longitude: 121)>
array([[[272.257  , 272.6281 , ..., 253.52705, 252.94325],
        [272.3083 , 272.84683, ..., 255.66464, 254.58453],
        ...,
        [300.02005, 300.00497, ..., 300.75168, 300.72153],
        [300.10904, 300.02307, ..., 300.72604, 300.68985]],

       [[285.91827, 286.89883, ..., 265.65717, 265.6979 ],
        [286.9094 , 287.2307 , ..., 264.88028, 264.73093],
        ...,
        [300.01553, 300.06833, ..., 301.36264, 301.24496],
        [300.09396, 300.16638, ..., 301.09564, 300.9689 ]],

       ...,

       [[274.08685, 273.73236, ..., 249.83717, 253.38223],
        [274.00992, 274.1321 , ..., 252.88593, 257.21088],
        ...,
        [299.23712, 299.32913, ..., 299.57806, 299.43475],
        [299.1285 , 299.1602 , ..., 299.52676, 299.4815 ]],

       [[283.8727 , 283.8003 , ..., 262.48926, 261.13156],
        [283.79425, 284.0145 , ..., 265.26645, 263.5437 ],
        ...,
        [299.41965, 299.3608 , ..., 300.91763, 300.82712],
        [299.6218 , 299.53882, ..., 300.97647, 300.86633]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2018-01-01 ... 2018-12-31T12:00:00
Attributes:
    units:      K
    long_name:  2 metre temperature

In [67]:
d_2019

<xarray.Dataset>
Dimensions:    (longitude: 121, latitude: 125, time: 730)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2019-01-01 ... 2019-12-31T12:00:00
Data variables:
    t2m        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-06-19 14:49:37 GMT by grib_to_netcdf-2.28.1: /opt/ecmw...

In [68]:
d_1990 = xr.open_dataset('1990.nc')

In [69]:
d_1990['t2m'].loc["1990-12-01":"1990-12-31"]

<xarray.DataArray 't2m' (time: 62, latitude: 125, longitude: 121)>
[937750 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 1990-12-01 ... 1990-12-31T12:00:00
Attributes:
    units:      K
    long_name:  2 metre temperature

In [70]:
a = d_2022['t2m'].loc["2022-12-01":"2022-12-31"]
a

<xarray.DataArray 't2m' (time: 62, latitude: 125, longitude: 121)>
[937750 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2022-12-01 ... 2022-12-31T12:00:00
Attributes:
    units:      K
    long_name:  2 metre temperature

In [71]:
b = d_2023['t2m'].loc["2023-12-01":"2023-12-31"]

In [72]:
a.combine_first(b)

<xarray.DataArray 't2m' (time: 124, latitude: 125, longitude: 121)>
array([[[282.7762 , 283.15704, 282.90118, ..., 262.5512 , 262.2284 ,
         264.00604],
        [282.94876, 282.05475, 281.26038, ..., 263.95547, 264.33032,
         264.2247 ],
        [281.66946, 280.4794 , 279.90817, ..., 266.00534, 266.0544 ,
         264.38538],
        ...,
        [299.85056, 299.74792, 299.7018 , ..., 299.617  , 299.8238 ,
         299.8952 ],
        [299.89072, 299.73602, 299.6646 , ..., 299.30164, 299.59024,
         299.8357 ],
        [300.08856, 299.9785 , 299.79254, ..., 299.03387, 299.21686,
         299.52777]],

       [[286.6454 , 286.632  , 286.64984, ..., 269.26608, 267.65506,
         266.9187 ],
        [285.31104, 285.1831 , 285.12213, ..., 269.3256 , 268.61008,
         268.0701 ],
        [282.43854, 282.77026, 282.9428 , ..., 270.86224, 269.9117 ,
         268.70676],
...
        [299.42163, 299.45663, 299.51642, ..., 301.0855 , 301.1074 ,
         301.0622 ],
        [299.50186, 299.47122, 299.5208 , ..., 300.99802, 301.0403 ,
         300.9922 ],
        [299.61267, 299.5879 , 299.56894, ..., 300.75302, 300.7545 ,
         300.68887]],

       [[284.84784, 284.26746, 285.4472 , ..., 267.58942, 266.87488,
         266.61093],
        [284.87994, 284.5737 , 284.55182, ..., 267.94086, 267.41296,
         267.1053 ],
        [283.4523 , 283.4523 , 283.64188, ..., 268.98935, 268.47165,
         267.24234],
        ...,
        [300.63638, 300.58972, 300.55472, ..., 301.3553 , 301.35675,
         301.39758],
        [300.6524 , 300.57513, 300.562  , ..., 301.35092, 301.3684 ,
         301.41217],
        [300.62033, 300.45117, 300.27036, ..., 301.3378 , 301.36258,
         301.418  ]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2022-12-01 ... 2023-12-31T12:00:00
Attributes:
    units:      K
    long_name:  2 metre temperature

In [73]:
a = a.to_numpy() + b.to_numpy()
a = xr.DataArray(a)
a

<xarray.DataArray (dim_0: 62, dim_1: 125, dim_2: 121)>
array([[[564.70465, 565.27795, 565.1388 , ..., 521.2686 , 521.0639 ,
         522.9713 ],
        [564.4572 , 563.6449 , 562.36633, ..., 525.4275 , 525.0426 ,
         524.03284],
        [560.4408 , 560.0615 , 559.16364, ..., 528.2517 , 527.6125 ,
         526.35034],
        ...,
        [600.48694, 600.04456, 599.8861 , ..., 599.37695, 599.72815,
         600.1276 ],
        [600.56067, 600.333  , 600.1201 , ..., 598.9858 , 599.39246,
         599.95435],
        [600.811  , 600.679  , 600.4523 , ..., 598.39136, 598.76245,
         599.5065 ]],

       [[575.9686 , 575.8094 , 576.50684, ..., 538.97   , 536.5511 ,
         535.857  ],
        [574.71594, 574.047  , 574.1231 , ..., 539.7251 , 538.50793,
         537.6194 ],
        [569.8325 , 570.2153 , 570.713  , ..., 542.43414, 541.13074,
         538.65564],
...
        [599.5117 , 599.58093, 599.6942 , ..., 601.2589 , 601.26587,
         601.1344 ],
        [599.9281 , 599.92426, 600.01843, ..., 601.2963 , 601.3357 ,
         601.234  ],
        [600.1326 , 600.1391 , 600.08295, ..., 601.1183 , 601.1153 ,
         601.02734]],

       [[565.81067, 565.69147, 567.27435, ..., 532.70667, 531.56665,
         531.9275 ],
        [565.16595, 565.062  , 565.2261 , ..., 532.5449 , 531.72546,
         531.63495],
        [560.12646, 561.36566, 561.99554, ..., 534.8236 , 534.01587,
         531.2261 ],
        ...,
        [601.3988 , 601.37   , 601.36475, ..., 601.4647 , 601.4468 ,
         601.5115 ],
        [601.48926, 601.4238 , 601.43604, ..., 601.5719 , 601.57007,
         601.6004 ],
        [601.5509 , 601.3683 , 601.1741 , ..., 601.70605, 601.6609 ,
         601.6985 ]]], dtype=float32)
Dimensions without coordinates: dim_0, dim_1, dim_2

In [74]:
d_2017 = xr.open_dataset('2017.nc')
d_2017['time']

<xarray.DataArray 'time' (time: 730)>
array(['2017-01-01T00:00:00.000000000', '2017-01-01T12:00:00.000000000',
       '2017-01-02T00:00:00.000000000', ..., '2017-12-30T12:00:00.000000000',
       '2017-12-31T00:00:00.000000000', '2017-12-31T12:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2017-01-01 ... 2017-12-31T12:00:00
Attributes:
    long_name:  time

In [75]:
d_2017 = xr.open_dataset('2017.nc')
d_2017

<xarray.Dataset>
Dimensions:    (longitude: 121, latitude: 125, time: 730)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
  * time       (time) datetime64[ns] 2017-01-01 ... 2017-12-31T12:00:00
Data variables:
    t2m        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-06-18 03:36:05 GMT by grib_to_netcdf-2.28.1: /opt/ecmw...

In [76]:
d = xr.open_dataset('2018.nc')
d['time']

<xarray.DataArray 'time' (time: 730)>
array(['2018-01-01T00:00:00.000000000', '2018-01-01T12:00:00.000000000',
       '2018-01-02T00:00:00.000000000', ..., '2018-12-30T12:00:00.000000000',
       '2018-12-31T00:00:00.000000000', '2018-12-31T12:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 ... 2018-12-31T12:00:00
Attributes:
    long_name:  time

In [77]:
d = d['t2m'].loc["2018-12-01":"2018-12-31"]

In [115]:
l = d.sel(time=slice("2018-12-01","2018-12-01"))
m = d.sel(time=slice("2018-12-02","2018-12-02"))
m[0][1][1].item()

282.61309814453125

In [121]:
a = l.sum(dim="time")
a = a / 2
b = l.sum(dim="time")
b = b / 2
a = a + b
a.rename()

In [107]:
k = xr.concat([a,b],dim='time')
k

<xarray.DataArray 't2m' (time: 2, latitude: 125, longitude: 121)>
array([[[564.1476 , 565.06024, 565.57465, ..., 517.96533, 517.90045,
         523.8335 ],
        [563.4325 , 563.9439 , 563.72974, ..., 526.6138 , 522.31445,
         521.4304 ],
        [561.577  , 561.72034, 561.98584, ..., 532.67505, 528.4436 ,
         525.1203 ],
        ...,
        [600.562  , 600.3508 , 600.49414, ..., 601.5834 , 601.4657 ,
         601.21826],
        [600.46246, 600.4776 , 600.61633, ..., 600.808  , 600.73706,
         600.40967],
        [600.59375, 600.7461 , 601.1957 , ..., 600.4595 , 600.4806 ,
         600.1472 ]],

       [[564.1476 , 565.06024, 565.57465, ..., 517.96533, 517.90045,
         523.8335 ],
        [563.4325 , 563.9439 , 563.72974, ..., 526.6138 , 522.31445,
         521.4304 ],
        [561.577  , 561.72034, 561.98584, ..., 532.67505, 528.4436 ,
         525.1203 ],
        ...,
        [600.562  , 600.3508 , 600.49414, ..., 601.5834 , 601.4657 ,
         601.21826],
        [600.46246, 600.4776 , 600.61633, ..., 600.808  , 600.73706,
         600.40967],
        [600.59375, 600.7461 , 601.1957 , ..., 600.4595 , 600.4806 ,
         600.1472 ]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0
Dimensions without coordinates: time

In [138]:
d = d.sel(time=slice("2018-12-1","2018-12-1"))
d.min(dim='time')

<xarray.DataArray 't2m' (latitude: 125, longitude: 121)>
array([[281.4983 , 282.01572, 282.18015, ..., 256.65875, 257.0902 ,
        258.79333],
       [281.18298, 281.53146, 281.22372, ..., 259.80405, 258.41318,
        258.47202],
       [280.66406, 280.71835, 280.73648, ..., 262.4259 , 260.95508,
        260.6428 ],
       ...,
       [299.57956, 299.4091 , 299.45737, ..., 300.44547, 300.72302,
        300.4002 ],
       [299.61273, 299.5675 , 299.59464, ..., 299.57654, 299.9235 ,
        300.10754],
       [299.73193, 299.76962, 300.0095 , ..., 299.28088, 299.3382 ,
        299.48755]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 68.0 68.25 68.5 68.75 ... 97.5 97.75 98.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 6.75 6.5 6.25 6.0

In [122]:
time_list = []
for x in range(1,32):
    time_list.append(f"12-{x}")
print(time_list)

['12-1', '12-2', '12-3', '12-4', '12-5', '12-6', '12-7', '12-8', '12-9', '12-10', '12-11', '12-12', '12-13', '12-14', '12-15', '12-16', '12-17', '12-18', '12-19', '12-20', '12-21', '12-22', '12-23', '12-24', '12-25', '12-26', '12-27', '12-28', '12-29', '12-30', '12-31']


In [125]:
type('12-1')

str

In [145]:
import numpy as np
x = np.random.choice([True,False],size = (31,125,121))
x

array([[[ True,  True,  True, ...,  True,  True,  True],
        [False, False,  True, ..., False, False, False],
        [False,  True, False, ...,  True,  True,  True],
        ...,
        [False, False,  True, ...,  True,  True,  True],
        [False,  True,  True, ..., False,  True,  True],
        [False, False, False, ..., False, False,  True]],

       [[ True, False,  True, ..., False,  True, False],
        [False, False,  True, ..., False,  True,  True],
        [False, False, False, ..., False, False,  True],
        ...,
        [False,  True,  True, ..., False, False,  True],
        [False,  True, False, ..., False, False, False],
        [ True,  True, False, ..., False,  True,  True]],

       [[False,  True, False, ..., False, False,  True],
        [False,  True, False, ..., False,  True,  True],
        [False, False, False, ..., False,  True, False],
        ...,
        [ True, False,  True, ..., False, False, False],
        [ True,  True, False, ...,  True,  Tr